"""
Render a size-banded MQS table to overleaf/paper/latex/tables/tab_mqs_size_banded.tex.

The user (prompts 19, 20, 32) asked to organise the MQS comparison by
model size so a 100B model is not directly compared with a 30B model.
Open-weight model sizes are public; proprietary model sizes are
estimated, in some cases from a Microsoft paper that listed leaked
parameter counts (Abacha et al. 2024, MEDEC; flagged by the authors as
estimates).

Bands used:
    Tiny       : <=8B parameters
    Small      : 8B-30B
    Medium     : 30B-100B
    Large      : >100B (or "frontier-class" for unknown proprietary)

We mark proprietary parameter counts with an asterisk and footnote them
as estimates so a reviewer can see we are not claiming exact knowledge
of those numbers.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[2]
RESULTS = REPO / "release" / "results"
OUT = REPO / "overleaf" / "paper" / "latex" / "tables" / "tab_mqs_size_banded.tex"

# Each entry: (model_alias, display, params_b, family_label, is_estimated)
# Estimates marked is_estimated=True render with an asterisk in the table.
MODELS = [
    # Tiny (≤8B)
    ("medgemma_4b",          "MedGemma 4B",          4,    "Open-weight medical",     False),
    ("gpt_4o_mini",          "GPT-4o Mini",          8,    "Proprietary efficient",   True),
    # Small (8B–30B)
    ("gemini_3_1_flash_lite","Gemini 3.1 Flash-Lite", 25,  "Proprietary efficient",   True),
    ("gemma_3_27b",          "Gemma 3 27B",           27,  "Open-weight general",     False),
    ("medgemma_27b",         "MedGemma 27B",          27,  "Open-weight medical",     False),
    # Medium (30B–100B)
    ("aya_expanse",          "Aya Expanse 32B",       32,  "Open-weight multilingual",False),
    ("llama_3_3_70b",        "Llama 3.3 70B",         70,  "Open-weight general",     False),
    # Medium-large (~100-200B)
    ("cohere_command_a",     "Command A",             111, "Proprietary enterprise",  False),
    ("claude_haiku_4_5",     "Claude Haiku 4.5",      150, "Proprietary efficient",   True),
    ("gpt_5_mini",           "GPT-5 Mini",            175, "Proprietary efficient",   True),
    ("gemini_3_flash",       "Gemini 3 Flash",        175, "Proprietary efficient",   True),
    # Large (>200B)
    ("claude_opus_4_7",      "Claude Opus 4.7",       300, "Proprietary frontier",    True),
    ("gemini_3_pro",         "Gemini 3 Pro",          400, "Proprietary frontier",    True),
    # MoE: report active params with a separate note
    ("llama_4_maverick",     "Llama 4 Maverick",      17,  "Open-weight MoE (400B total)", False),
]

BAND_BOUNDS = [
    ("Tiny ($\\leq$ 8B)",       0,    9),
    ("Small (8-30B)",          9,    31),
    ("Medium (30-100B)",       31,   101),
    ("Large (100-200B)",       101,  201),
    ("Frontier (>200B)",       201,  10**6),
]


def main() -> None:
    df = pd.read_csv(RESULTS / "mqs_per_model__gpt_4o_mini.csv")
    piv = df.pivot_table(index="gen_model", columns=["dataset", "lang"], values="mqs_mean").round(3)

    rows = []
    for alias, display, params, family, est in MODELS:
        if alias not in piv.index:
            continue
        size_str = f"{params}B" + ("$^*$" if est else "")
        ex_en = piv.get(("expert", "en"), pd.Series()).get(alias)
        ex_hi = piv.get(("expert", "hi"), pd.Series()).get(alias)
        ex_mr = piv.get(("expert", "mr"), pd.Series()).get(alias)
        ne_en = piv.get(("non_expert", "en"), pd.Series()).get(alias)
        ne_hi = piv.get(("non_expert", "hi"), pd.Series()).get(alias)
        ne_mr = piv.get(("non_expert", "mr"), pd.Series()).get(alias)

        def fmt(x):
            return "---" if pd.isna(x) else f"{x:.2f}"
        rows.append({
            "alias": alias, "display": display, "params": params, "size_str": size_str,
            "family": family,
            "ex_en": fmt(ex_en), "ex_hi": fmt(ex_hi), "ex_mr": fmt(ex_mr),
            "ne_en": fmt(ne_en), "ne_hi": fmt(ne_hi), "ne_mr": fmt(ne_mr),
        })

    # Group rows by size band
    grouped = []
    for band_label, lo, hi in BAND_BOUNDS:
        in_band = [r for r in rows if lo <= r["params"] <= hi - 1]
        # Llama 4 Maverick (17B active / 400B total): we put it in Small band by active params
        if not in_band:
            continue
        grouped.append((band_label, in_band))

    lines = [
        "% Auto-generated by scoring/pipeline/render_size_banded_table.py.",
        "% Models grouped by parameter count. Proprietary sizes marked with * are estimates",
        "% (e.g. Microsoft leaked figures, vendor benchmarks). Open-weight sizes are exact.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{MQS by model under the GPT-4o-mini judge, grouped by size band so the cost-vs-quality comparison is on like-for-like models. Open-weight sizes are exact; proprietary sizes (marked with $^*$) are estimates from leaked or vendor-reported figures and are approximate. Llama 4 Maverick is a sparse mixture-of-experts model with 17B active parameters and roughly 400B total. ``Expert'' is the doctor-edited 149-question track, ``Non-expert'' is the 231-question community-sourced track. Cells are mean MQS across three runs and all questions for which the model produced a valid response.}",
        "\\label{tab:mqs_size_banded}",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\small",
        "\\begin{tabular}{llcccc|ccc}",
        "\\toprule",
        "& & & \\multicolumn{3}{c}{\\textbf{Expert (149)}} & \\multicolumn{3}{c}{\\textbf{Non-expert (231)}} \\\\",
        "\\cmidrule(lr){4-6} \\cmidrule(lr){7-9}",
        "\\textbf{Model} & \\textbf{Family} & \\textbf{Size} & \\textbf{EN} & \\textbf{HI} & \\textbf{MR} & \\textbf{EN} & \\textbf{HI} & \\textbf{MR} \\\\",
        "\\midrule",
    ]
    for band_label, band_rows in grouped:
        lines.append(f"\\multicolumn{{9}}{{l}}{{\\textit{{{band_label}}}}} \\\\")
        for r in band_rows:
            lines.append(
                f"{r['display']} & {r['family']} & {r['size_str']} & "
                f"{r['ex_en']} & {r['ex_hi']} & {r['ex_mr']} & "
                f"{r['ne_en']} & {r['ne_hi']} & {r['ne_mr']} \\\\"
            )
        lines.append("\\midrule")
    # Replace last midrule with bottomrule
    if lines[-1] == "\\midrule":
        lines[-1] = "\\bottomrule"
    else:
        lines.append("\\bottomrule")
    lines += [
        "\\end{tabular}",
        "\\\\[3pt]",
        "{\\footnotesize $^*$Estimated parameter count; exact figure not disclosed by vendor.}",
        "\\end{table}",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
