import os,re,json,asyncio,aiohttp,logging,pandas as pd
from pathlib import Path
from dotenv import load_dotenv,find_dotenv
logging.basicConfig(level=logging.INFO,format="%(asctime)s - %(message)s")
logger=logging.getLogger(__name__)
load_dotenv(find_dotenv())
OR_KEY=os.getenv("OPENROUTER_API_KEY","").strip()
RUBRIC_MAP = {
    "Antenatal & Maternal Health Care": "[\"Response accurately describes the importance and recommended schedule for regular antenatal check-ups (ANC).\", \"Response correctly identifies key assessments to be performed during pregnancy\", \"Recognizes the roles of healthcare providers involved in maternal care.\", \"Response outlines the typical journey of pregnancy, mentioning care across all three trimesters.\", \"Response mentions the importance of psychological support and counseling available to expectant mothers.\", \"Identify community resources available for maternal health support.\", \"Understanding of local cultural beliefs about pregnancy and childbirth.\", \"The response considers the patient\u2019s location, literacy, and support systems in recommendations.\", \"Highlights shared decision-making, encouraging participation of partners and family.\", \"Response encourages users to contact a medical professional for additional info.\", \"Uses everyday analogies, metaphors, or local references for clarity.\", \"Presents suggestions in clear steps that suit rural and semiurban women\u2019s realities.\", \"Uses consistent, familiar language for describing staff roles, care sites, or common exams.\", \"Define medical abbreviations (ANC, BP, FHR) in plain language.\", \"Avoid jargon or explain all complex terms at first use.\"]",
    "Nutrition, Diet & Supplementation": "[\"Discuss the importance of a balanced diet for pregnant and breastfeeding mothers.\", \"Identify key micronutrients and its sources essential for maternal health and fetal development.\", \"Outline the potential risks of excessive supplementation during pregnancy.\", \"Provides dietary guidance consistent with managing common health challenges related to pregnancy.\", \"Explains how to balance the entire diet\u2014from meal plans to supplementation and self-care.\", \"Covers key topics related to food safety, dietary balance, and supplementation comprehensively.\", \"Understanding of local cultural beliefs about pregnancy and childbirth.\", \"Customizes recommendations to fit available foods and common food habits.\", \"Respond to affordability or access issues (suggest community programs if relevant).\", \"Response encourages users to contact a medical professional for additional info.\", \"Explains food choices and health impacts in plain, conversational language.\", \"Mentions when to consult health workers before starting new supplements or diets.\", \"Understanding of the health implications of underweight and overweight before pregnancy.\", \"Translate micronutrient or supplement names into local language and common foods.\", \"Describes benefits, risks, and deficiency signs without clinical or chemical jargon.\"]",
    "Mental, Emotional & Social Well-being": "[\"Identify common psychological health issues during pregnancy and postpartum, and explain their potential effects on both maternal and fetal well-being.\", \"Discuss the impact of stress on maternal health and fetal development.\", \"Discuss the significance of community resources in supporting maternal mental health.\", \"Describe the importance of family support in promoting maternal mental health.\", \"Discuss the effects of isolation and loneliness on maternal mental health and child health.\", \"Discuss the importance of self-care practices for mothers in maintaining mental health.\", \"Considers local beliefs about mental and emotional health within patient responses.\", \"Recognizes resource limitations and suggests practical workarounds.\", \"Recommends methods that are sensitive, respectful, and safe for all users.\", \"Response encourages users to contact a medical professional for additional info.\", \"Normalize discussion of feelings with supportive phrasing.\", \"Clarity of information provided about postpartum self-care.\", \"Defines all mental health diagnostic labels clearly, avoids jargon and abbreviations.\", \"Avoid psychiatric diagnostic labels except where necessary, and explain meaning gently.\", \"Lists local or national mental health supports in an accessible format.\"]",
    "Clinical Procedures & Guidelines": "[\"Identify and describe the purpose of specific diagnostic tests relevant to the clinical scenario.\", \"Explain the steps involved in performing a particular clinical procedure, including preparation and aftercare.\", \"Outline the recommended screening schedules for various populations based on age, and risk factors.\", \"Discuss the importance of informed consent prior to conducting diagnostic tests or procedures\", \"Discuss the importance of follow-up care and monitoring after diagnostic tests or procedures.\", \"Provides information on importance of timeliness for check ups.\", \"Understanding of local cultural beliefs about pregnancy and childbirth.\", \"Considers family role in supporting or delivering care.\", \"Mentions alternative approaches consistent with safe and effective care where standard care is unavailable.\", \"Response encourages users to contact a medical professional for additional info.\", \"Clearly states each procedure\u2019s objective, expected sensations, and outcomes.\", \"Offers structured self-monitoring and follow-up instructions.\", \"Defines all technical terms, tests, and tool names in patient-friendly language.\", \"Clarity of explanation regarding the purpose and necessity of medical tests during pregnancy.\", \"Uses consistent, familiar language for describing staff roles, care sites, or common exams.\"]",
    "Medication & Vaccination Safety": "[\"Explain the importance of consulting healthcare providers before taking any medication or supplement during pregnancy.\", \"Details safe medication use and vaccination  practices considering pregnancy-specific risks.\", \"Highlight the role of prenatal vitamins and their recommended dosages.\", \"Identify resources for pregnant women to obtain reliable information about medication safety.\", \"Encourages reporting of side effects, adverse outcomes, or uncertain medication exposures.\", \"Offers access to official or community sources for medication authenticity or information.\", \"Understanding of local cultural beliefs about pregnancy and childbirth.\", \"Discuss the impact of maternal lifestyle choices on medication efficacy and safety during pregnancy.\", \"Adapts medical advice for limited access or poor supply chain settings.\", \"Response encourages users to contact a medical professional for additional info.\", \"Gives practical, relatable medication and vaccine instructions.\", \"Effectively explains the risk-benefit analysis of a medication in a simple way.\", \"Defines relevant pharmacological terms in an accessible manner.\", \"Clarity of explanation regarding the purpose and necessity of medical tests during pregnancy.\", \"Explains side effects and uses in simple, non-alarming phrases.\"]",
    "Reproductive & Sexual Health (Beyond Pregnancy)": "[\"Explain the different methods of family planning and contraception and their effectiveness.\", \"Identify lifestyle factors that can enhance or hinder reproductive health.\", \"Discuss the importance of regular gynecological check-ups for reproductive health.\", \"Identify resources available for individuals seeking information on reproductive health.\", \"Explains disease prevention and the patient referral process\", \"Addresses menstrual irregularities, pain, and other common concerns.\", \"Describe the impact of cultural beliefs on reproductive health practices.\", \"Discuss the importance of communication between partners regarding sexual health.\", \"Outline the guidelines for safe sexual practices during and after pregnancy to prevent infections.\", \"Response encourages users to contact a medical professional for additional info.\", \"Offers calm, non-judgmental, and inclusive language for all users.\", \"Advises how to ask for privacy, consent, or withdrawal of care.\", \"Explains all contraceptive and sexual health choices in a relatable manner.\", \"Translates medical, legal, and sexual health terms using plain and/or local language.\", \"Provides relevant contraceptive options in a clear and understandable manner.\"]",
    "Health Systems, Access & Provider Support": "[\"Discuss the role of primary care providers in enhancing patient access to healthcare.\", \"Explain the importance of community health systems in promoting public health.\", \"Identify policies that can support improved access to healthcare services.\", \"Outlines community support available to seek access to health system\", \"Outline process for reporting side effects or seeking advice.\", \"Always mention available grievance or escalation resources.\", \"Highlights local advocacy or support networks (e.g., women\u2019s groups, SHGs).\", \"Suggest safe alternatives like friends and family if first-line options unavailable locally.\", \"Advise regarding local customs (e.g., avoiding injections in pregnancy, if relevant).\", \"Clarity of information provided about postpartum self-care.\", \"Model conversations a patient could have with local health worker.\", \"Frames advice positively, encouraging proactive, non-confrontational self-advocacy.\", \"Explain facility types with local equivalents/terms.\", \"Explains abbreviations for agencies, programs, and staff.\", \"Provide generic drug names in English AND local names/brands as per national protocol.\"]",
    "Infection Prevention & Hygiene Practices": "[\"Demonstrates correct understanding of infection risks and protective measures relevant to maternal health.\", \"Describe the signs and symptoms of common infections that can occur during pregnancy and postpartum.\", \"Discuss the impact of maternal infections on fetal development and postpartum recovery.\", \"Discuss the importance of follow-up care in preventing infections after childbirth.\", \"Identify community resources available for education on infection prevention during pregnancy.\", \"Explains infection prevention strategies that protect both the mother and the developing baby, in clear, actionable language.\", \"Understanding of local cultural beliefs about infection in pregnancy and childbirth.\", \"Provides guidance on community or family involvement in maintaining safe environments.\", \"Addresses stigma, beliefs, and local customs on infection prevention and reporting.\", \"Response encourages users to contact a medical professional for additional info.\", \"Clarity of information provided about self-care during pregnancy.\", \"Points out when and where to seek medical care for signs of infection.\", \"Translates infection, vaccine, and sanitation vocabulary for non-expert understanding.\", \"Delivers advice in a format suitable for those with lower literacy or educational background.\", \"Makes symptoms and risks relatable to community language and observations.\"]",
    "Symptom Interpretation & Danger Sign Recognition": "[\"Describe the significance of a medical condition and its potential causes and implications for mother.\", \"Recognize the importance of monitoring vital signs in symptomatic patients.\", \"Uses best practices to explain key vitals in assessment\", \"Explain the importance of patient history in interpreting symptoms accurately.\", \"Recognize the role of family history in assessing risk for certain symptoms.\", \"Mention associated or secondary symptoms to watch for.\", \"Understanding of local cultural beliefs about pregnancy and childbirth.\", \"Considers family and community influence on symptom recognition and action.\", \"Acknowledges varying levels of healthcare access and resources.\", \"Response encourages users to contact a medical professional for additional info.\", \"Maintains a supportive and reassuring tone while clearly conveying urgency.\", \"Always cues about when and how to get immediate medical assistance.\", \"Ensures advice is immediately actionable for a broad audience.\", \"Avoid jargon or explain all complex terms at first use.\", \"Relate complex danger sign descriptions to local expressions or symptoms\"]",
    "Risk & Complication Management": "[\"Recognize and explain the warning signs or complications that may indicate a medical emergency during pregnancy.\", \"Describe the risk factors associated with high-risk pregnancies, including maternal age, pre-existing medical conditions, and multiple gestations.\", \"Describes relevant diagnostic and monitoring methods applicable to pregnancy risk assessment.\", \"Summarize the management strategies for common complications, including self-monitoring protocols.\", \"Discuss the support systems available for patients for managing high-risk pregnancies.\", \"Explain the role of follow-up care and monitoring after a pregnancy complicated by high-risk conditions.\", \"Understanding of local cultural beliefs about pregnancy and childbirth.\", \"Evaluate the impact of lifestyle factors, such as nutrition and exercise, on pregnancy outcomes in high-risk patients.\", \"Discuss the role of antenatal care in preventing complications and managing high-risk conditions.\", \"Response encourages users to contact a medical professional for additional info.\", \"Breaks down potential risk factors in simple, memorable terms.\", \"Clarity of information provided about postpartum self-care.\", \"Explains all complication names and protocols in clear, familiar language, defining any medical terms or abbreviations used.\", \"Clarity of explanation regarding the purpose and necessity of medical tests during pregnancy.\", \"Relates complex medication plans or monitoring routines to everyday activities.\"]"
}
AXIS_MAP = {
    "Antenatal & Maternal Health Care": "{\"Accuracy\": [\"Response accurately describes the importance and recommended schedule for regular antenatal check-ups (ANC).\", \"Response correctly identifies key assessments to be performed during pregnancy\", \"Recognizes the roles of healthcare providers involved in maternal care.\"], \"Completeness\": [\"Response outlines the typical journey of pregnancy, mentioning care across all three trimesters.\", \"Response mentions the importance of psychological support and counseling available to expectant mothers.\", \"Identify community resources available for maternal health support.\"], \"Context Awareness\": [\"Understanding of local cultural beliefs about pregnancy and childbirth.\", \"The response considers the patient\u2019s location, literacy, and support systems in recommendations.\", \"Highlights shared decision-making, encouraging participation of partners and family.\"], \"Communication\": [\"Response encourages users to contact a medical professional for additional info.\", \"Uses everyday analogies, metaphors, or local references for clarity.\", \"Presents suggestions in clear steps that suit rural and semiurban women\u2019s realities.\"], \"Terminology Accessibility\": [\"Uses consistent, familiar language for describing staff roles, care sites, or common exams.\", \"Define medical abbreviations (ANC, BP, FHR) in plain language.\", \"Avoid jargon or explain all complex terms at first use.\"]}",
    "Nutrition, Diet & Supplementation": "{\"Accuracy\": [\"Discuss the importance of a balanced diet for pregnant and breastfeeding mothers.\", \"Identify key micronutrients and its sources essential for maternal health and fetal development.\", \"Outline the potential risks of excessive supplementation during pregnancy.\"], \"Completeness\": [\"Provides dietary guidance consistent with managing common health challenges related to pregnancy.\", \"Explains how to balance the entire diet\u2014from meal plans to supplementation and self-care.\", \"Covers key topics related to food safety, dietary balance, and supplementation comprehensively.\"], \"Context Awareness\": [\"Understanding of local cultural beliefs about pregnancy and childbirth.\", \"Customizes recommendations to fit available foods and common food habits.\", \"Respond to affordability or access issues (suggest community programs if relevant).\"], \"Communication\": [\"Response encourages users to contact a medical professional for additional info.\", \"Explains food choices and health impacts in plain, conversational language.\", \"Mentions when to consult health workers before starting new supplements or diets.\"], \"Terminology Accessibility\": [\"Understanding of the health implications of underweight and overweight before pregnancy.\", \"Translate micronutrient or supplement names into local language and common foods.\", \"Describes benefits, risks, and deficiency signs without clinical or chemical jargon.\"]}",
    "Mental, Emotional & Social Well-being": "{\"Accuracy\": [\"Identify common psychological health issues during pregnancy and postpartum, and explain their potential effects on both maternal and fetal well-being.\", \"Discuss the impact of stress on maternal health and fetal development.\", \"Discuss the significance of community resources in supporting maternal mental health.\"], \"Completeness\": [\"Describe the importance of family support in promoting maternal mental health.\", \"Discuss the effects of isolation and loneliness on maternal mental health and child health.\", \"Discuss the importance of self-care practices for mothers in maintaining mental health.\"], \"Context Awareness\": [\"Considers local beliefs about mental and emotional health within patient responses.\", \"Recognizes resource limitations and suggests practical workarounds.\", \"Recommends methods that are sensitive, respectful, and safe for all users.\"], \"Communication\": [\"Response encourages users to contact a medical professional for additional info.\", \"Normalize discussion of feelings with supportive phrasing.\", \"Clarity of information provided about postpartum self-care.\"], \"Terminology Accessibility\": [\"Defines all mental health diagnostic labels clearly, avoids jargon and abbreviations.\", \"Avoid psychiatric diagnostic labels except where necessary, and explain meaning gently.\", \"Lists local or national mental health supports in an accessible format.\"]}",
    "Clinical Procedures & Guidelines": "{\"Accuracy\": [\"Identify and describe the purpose of specific diagnostic tests relevant to the clinical scenario.\", \"Explain the steps involved in performing a particular clinical procedure, including preparation and aftercare.\", \"Outline the recommended screening schedules for various populations based on age, and risk factors.\"], \"Completeness\": [\"Discuss the importance of informed consent prior to conducting diagnostic tests or procedures\", \"Discuss the importance of follow-up care and monitoring after diagnostic tests or procedures.\", \"Provides information on importance of timeliness for check ups.\"], \"Context Awareness\": [\"Understanding of local cultural beliefs about pregnancy and childbirth.\", \"Considers family role in supporting or delivering care.\", \"Mentions alternative approaches consistent with safe and effective care where standard care is unavailable.\"], \"Communication\": [\"Response encourages users to contact a medical professional for additional info.\", \"Clearly states each procedure\u2019s objective, expected sensations, and outcomes.\", \"Offers structured self-monitoring and follow-up instructions.\"], \"Terminology Accessibility\": [\"Defines all technical terms, tests, and tool names in patient-friendly language.\", \"Clarity of explanation regarding the purpose and necessity of medical tests during pregnancy.\", \"Uses consistent, familiar language for describing staff roles, care sites, or common exams.\"]}",
    "Medication & Vaccination Safety": "{\"Accuracy\": [\"Explain the importance of consulting healthcare providers before taking any medication or supplement during pregnancy.\", \"Details safe medication use and vaccination  practices considering pregnancy-specific risks.\", \"Highlight the role of prenatal vitamins and their recommended dosages.\"], \"Completeness\": [\"Identify resources for pregnant women to obtain reliable information about medication safety.\", \"Encourages reporting of side effects, adverse outcomes, or uncertain medication exposures.\", \"Offers access to official or community sources for medication authenticity or information.\"], \"Context Awareness\": [\"Understanding of local cultural beliefs about pregnancy and childbirth.\", \"Discuss the impact of maternal lifestyle choices on medication efficacy and safety during pregnancy.\", \"Adapts medical advice for limited access or poor supply chain settings.\"], \"Communication\": [\"Response encourages users to contact a medical professional for additional info.\", \"Gives practical, relatable medication and vaccine instructions.\", \"Effectively explains the risk-benefit analysis of a medication in a simple way.\"], \"Terminology Accessibility\": [\"Defines relevant pharmacological terms in an accessible manner.\", \"Clarity of explanation regarding the purpose and necessity of medical tests during pregnancy.\", \"Explains side effects and uses in simple, non-alarming phrases.\"]}",
    "Reproductive & Sexual Health (Beyond Pregnancy)": "{\"Accuracy\": [\"Explain the different methods of family planning and contraception and their effectiveness.\", \"Identify lifestyle factors that can enhance or hinder reproductive health.\", \"Discuss the importance of regular gynecological check-ups for reproductive health.\"], \"Completeness\": [\"Identify resources available for individuals seeking information on reproductive health.\", \"Explains disease prevention and the patient referral process\", \"Addresses menstrual irregularities, pain, and other common concerns.\"], \"Context Awareness\": [\"Describe the impact of cultural beliefs on reproductive health practices.\", \"Discuss the importance of communication between partners regarding sexual health.\", \"Outline the guidelines for safe sexual practices during and after pregnancy to prevent infections.\"], \"Communication\": [\"Response encourages users to contact a medical professional for additional info.\", \"Offers calm, non-judgmental, and inclusive language for all users.\", \"Advises how to ask for privacy, consent, or withdrawal of care.\"], \"Terminology Accessibility\": [\"Explains all contraceptive and sexual health choices in a relatable manner.\", \"Translates medical, legal, and sexual health terms using plain and/or local language.\", \"Provides relevant contraceptive options in a clear and understandable manner.\"]}",
    "Health Systems, Access & Provider Support": "{\"Accuracy\": [\"Discuss the role of primary care providers in enhancing patient access to healthcare.\", \"Explain the importance of community health systems in promoting public health.\", \"Identify policies that can support improved access to healthcare services.\"], \"Completeness\": [\"Outlines community support available to seek access to health system\", \"Outline process for reporting side effects or seeking advice.\", \"Always mention available grievance or escalation resources.\"], \"Context Awareness\": [\"Highlights local advocacy or support networks (e.g., women\u2019s groups, SHGs).\", \"Suggest safe alternatives like friends and family if first-line options unavailable locally.\", \"Advise regarding local customs (e.g., avoiding injections in pregnancy, if relevant).\"], \"Communication\": [\"Clarity of information provided about postpartum self-care.\", \"Model conversations a patient could have with local health worker.\", \"Frames advice positively, encouraging proactive, non-confrontational self-advocacy.\"], \"Terminology Accessibility\": [\"Explain facility types with local equivalents/terms.\", \"Explains abbreviations for agencies, programs, and staff.\", \"Provide generic drug names in English AND local names/brands as per national protocol.\"]}",
    "Infection Prevention & Hygiene Practices": "{\"Accuracy\": [\"Demonstrates correct understanding of infection risks and protective measures relevant to maternal health.\", \"Describe the signs and symptoms of common infections that can occur during pregnancy and postpartum.\", \"Discuss the impact of maternal infections on fetal development and postpartum recovery.\"], \"Completeness\": [\"Discuss the importance of follow-up care in preventing infections after childbirth.\", \"Identify community resources available for education on infection prevention during pregnancy.\", \"Explains infection prevention strategies that protect both the mother and the developing baby, in clear, actionable language.\"], \"Context Awareness\": [\"Understanding of local cultural beliefs about infection in pregnancy and childbirth.\", \"Provides guidance on community or family involvement in maintaining safe environments.\", \"Addresses stigma, beliefs, and local customs on infection prevention and reporting.\"], \"Communication\": [\"Response encourages users to contact a medical professional for additional info.\", \"Clarity of information provided about self-care during pregnancy.\", \"Points out when and where to seek medical care for signs of infection.\"], \"Terminology Accessibility\": [\"Translates infection, vaccine, and sanitation vocabulary for non-expert understanding.\", \"Delivers advice in a format suitable for those with lower literacy or educational background.\", \"Makes symptoms and risks relatable to community language and observations.\"]}",
    "Symptom Interpretation & Danger Sign Recognition": "{\"Accuracy\": [\"Describe the significance of a medical condition and its potential causes and implications for mother.\", \"Recognize the importance of monitoring vital signs in symptomatic patients.\", \"Uses best practices to explain key vitals in assessment\"], \"Completeness\": [\"Explain the importance of patient history in interpreting symptoms accurately.\", \"Recognize the role of family history in assessing risk for certain symptoms.\", \"Mention associated or secondary symptoms to watch for.\"], \"Context Awareness\": [\"Understanding of local cultural beliefs about pregnancy and childbirth.\", \"Considers family and community influence on symptom recognition and action.\", \"Acknowledges varying levels of healthcare access and resources.\"], \"Communication\": [\"Response encourages users to contact a medical professional for additional info.\", \"Maintains a supportive and reassuring tone while clearly conveying urgency.\", \"Always cues about when and how to get immediate medical assistance.\"], \"Terminology Accessibility\": [\"Ensures advice is immediately actionable for a broad audience.\", \"Avoid jargon or explain all complex terms at first use.\", \"Relate complex danger sign descriptions to local expressions or symptoms\"]}",
    "Risk & Complication Management": "{\"Accuracy\": [\"Recognize and explain the warning signs or complications that may indicate a medical emergency during pregnancy.\", \"Describe the risk factors associated with high-risk pregnancies, including maternal age, pre-existing medical conditions, and multiple gestations.\", \"Describes relevant diagnostic and monitoring methods applicable to pregnancy risk assessment.\"], \"Completeness\": [\"Summarize the management strategies for common complications, including self-monitoring protocols.\", \"Discuss the support systems available for patients for managing high-risk pregnancies.\", \"Explain the role of follow-up care and monitoring after a pregnancy complicated by high-risk conditions.\"], \"Context Awareness\": [\"Understanding of local cultural beliefs about pregnancy and childbirth.\", \"Evaluate the impact of lifestyle factors, such as nutrition and exercise, on pregnancy outcomes in high-risk patients.\", \"Discuss the role of antenatal care in preventing complications and managing high-risk conditions.\"], \"Communication\": [\"Response encourages users to contact a medical professional for additional info.\", \"Breaks down potential risk factors in simple, memorable terms.\", \"Clarity of information provided about postpartum self-care.\"], \"Terminology Accessibility\": [\"Explains all complication names and protocols in clear, familiar language, defining any medical terms or abbreviations used.\", \"Clarity of explanation regarding the purpose and necessity of medical tests during pregnancy.\", \"Relates complex medication plans or monitoring routines to everyday activities.\"]}"
}
def norm(t):return re.sub(r"[^a-z0-9]","",str(t).lower())
def flatten(r):
    if not r or pd.isna(r):return ["General Quality"]
    if isinstance(r,str):
        try:return json.loads(r)
        except:return [x.strip() for x in r.split(";") if x.strip()]
    return list(r.keys()) if isinstance(r,dict) else (r if r else ["General Quality"])
def clean_j(t):
    if not t:return {}
    t=str(t).strip()
    if "```" in t:
        m=re.search(r"```(?:json)?(.*?)```",t,re.DOTALL);t=m.group(1).strip() if m else t
    m=re.search(r"\{.*\}",t,re.DOTALL);t=m.group() if m else t
    try:
        d=json.loads(t);s=d.get("scores",d);res={}
        for k,v in s.items():
            res[str(k).strip()]=(1 if (isinstance(v,(int,float)) and v>=0.5) or (isinstance(v,str) and v.strip().lower() in {"1","yes","true","pass"}) else 0)
        return res
    except:return {}
def calc_m(s,t):
    w={"Accuracy":.3,"Completeness":.25,"Context Awareness":.2,"Communication":.15,"Terminology Accessibility":.1}
    aj=AXIS_MAP.get(str(t).strip(),"{}");mqs=0.0;rl=flatten(RUBRIC_MAP.get(t));nm={norm(k):v for k,v in s.items()}
    try:
        ac=json.loads(aj)
        if ac:
            h=0
            for cat,m in ac.items():
                if m and cat in w:
                    sub=0
                    for mx in m:
                        val=s.get(mx)
                        if val is None:val=nm.get(norm(mx))
                        if val is None:
                            try:idx=str(rl.index(mx)+1);val=s.get(idx,0)
                            except:val=0
                        sub+=val
                    if len(m)>0:mqs+=(sub/len(m))*w[cat];h+=1
            if h==0:v=list(s.values());mqs=sum(v)/len(v) if v else 0.0
        else:v=list(s.values());mqs=sum(v)/len(v) if v else 0.0
    except Exception as e:
        logger.error(f"MQS fail: {e}");v=list(s.values());mqs=sum(v)/len(v) if v else 0.0
    return json.dumps(s),mqs
async def judge(session,q,a,resp,r,jm):
    rl=flatten(r);p=f"Question:\n{q}\n\nReference:\n{a}\n\nResponse:\n{resp}\n\nRubrics:\n"+"\n".join(f"{i+1}. {x}" for i,x in enumerate(rl))+"\n\nReturn JSON: {\"scores\": {\"<Exact Rubric Text>\": 0 or 1}}"
    u,h="https://openrouter.ai/api/v1/chat/completions",{"Authorization":f"Bearer {OR_KEY}","Content-Type":"application/json","HTTP-Referer":"https://localhost:3000","X-Title":"Eval"}
    pay={"model":jm,"messages":[{"role":"system","content":"Return valid JSON only. Use the exact rubric text as keys."},{"role":"user","content":p}],"temperature":0.0,"max_tokens":800}
    for i in range(5):
        try:
            async with session.post(u,headers=h,json=pay,timeout=60) as res:
                if res.status==200:
                    d=await res.json(); txt=d["choices"][0]["message"]["content"]
                    ret=clean_j(txt)
                    if not ret:
                        logger.warning(f"Invalid JSON from LLM: {txt[:200]}...")
                        return {}
                    return ret
                elif res.status==429:await asyncio.sleep(2)
                elif res.status==402:logger.error("Out of credits");os._exit(1)
                else:logger.error(f"Err {res.status}: {await res.text()}")
        except Exception as e:
            logger.error(f"Request fail: {e}")
            await asyncio.sleep(1)
    return {}


async def proc(session,row,col,idx,jm):
    theme=str(row.get("theme","")).strip();rubrics=RUBRIC_MAP.get(theme)
    if not rubrics:return idx,col,None,0.0
    scores=await judge(session,row.get("question",""),row.get("answer",""),str(row.get(col,"")),rubrics,jm)
    if not scores:return idx,col,None,0.0
    s_j,m_v=calc_m(scores,theme);return idx,col,s_j,m_v
async def run_rubric_job(inp: Path, out: Path, jm: str) -> None:
    import time
    if not inp.exists():
        logger.warning("Skipping rubric job (missing input): %s", inp)
        return
    out.parent.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(out) if out.exists() else pd.read_csv(inp)
    pat = re.compile(r"(.*)_run([1-3])$")
    cols = [c for c in df.columns if pat.match(c) and "judge" not in c]
    all_t = []
    for c in cols:
        m_n, r_n = pat.match(c).groups()
        sc, mq = f"{m_n}_judge_scores_run{r_n}", f"{m_n}_judge_mqs_run{r_n}"
        if sc not in df.columns:
            df[sc], df[mq] = "", 0.0
        df[sc] = df[sc].astype(object)
        for i in df.index:
            v = str(df.at[i, sc]).strip()
            if pd.notna(df.at[i, c]) and v in ["", "{}", "nan", "None"]:
                all_t.append((i, c, df.iloc[i]))
    if not all_t:
        logger.info("Rubric job nothing to do (or already filled): %s -> %s", inp.name, out.name)
        return
    logger.info("Rubric job %s -> %s (%d judge tasks)", inp.name, out.name, len(all_t))
    start_t = time.time()
    async with aiohttp.ClientSession() as s:
        batch_size = 50
        for i in range(0, len(all_t), batch_size):
            batch = all_t[i : i + batch_size]
            results = await asyncio.gather(*[proc(s, r, c, idx, jm) for idx, c, r in batch])
            for res in results:
                if res and res[2]:
                    idx, c, sv, mv = res
                    m_n, r_n = pat.match(c).groups()
                    df.at[idx, f"{m_n}_judge_scores_run{r_n}"], df.at[idx, f"{m_n}_judge_mqs_run{r_n}"] = sv, mv
            df.to_csv(out, index=False)
            elapsed = time.time() - start_t
            done = i + len(batch)
            avg_per_task = elapsed / done
            rem_tasks = len(all_t) - done
            rem_sec = avg_per_task * rem_tasks
            logger.info("Progress: %d/%d | Rem: %.1fm", done, len(all_t), rem_sec / 60)


async def main():
    repo = Path(__file__).resolve().parent.parent
    out_dir = repo / "outputs" / "rubric_scores"
    jm = os.getenv("RUBRIC_JUDGE_MODEL", "openai/gpt-4o-mini").strip() or "openai/gpt-4o-mini"
    jobs = [
        (repo / "outputs" / "llm_test_data_english_non_expert_230.csv", out_dir / "rubric_scores_non_expert_english_gpt.csv"),
        (repo / "outputs" / "llm_test_data_english_expert_150.csv", out_dir / "rubric_scores_expert_english_gpt.csv"),
        (repo / "outputs" / "llm_test_data_multilingual_non_expert_230.csv", out_dir / "rubric_scores_non_expert_multilingual_gpt.csv"),
        (repo / "outputs" / "llm_test_data_multilingual_expert_150.csv", out_dir / "rubric_scores_expert_multilingual_gpt.csv"),
    ]
    for inp, outp in jobs:
        await run_rubric_job(inp, outp, jm)


if __name__ == "__main__":
    asyncio.run(main())
